spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: update
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:hms_dev
    username: root
    password:

  mail:
    host: smtp.gmail.com
    port: 465
    username: divadchigozie@gmail.com
    password: nzbebtlxxpyfznqw
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
            required: true
#hms:
#  jwt:
#    secret_key: 5367566B59703373357638792F423F4528482B4D6251655468576D5A71347437

server:
  servlet:
    context-path: /api/v1


